### ISSUE TITLE
Global counting

### ISSUE THREAD

**Issue by shanemmattner** [ElectronVector/ravioli#3]
I inherited a legacy code-base with globals everywhere.  So I was surprised when ravioli only found 1 global in the 'worst' source file of the project (scores ~1500).  

After testing I found that declaring the globals above a 'const' variable made them appear to ravioli.  But after removing const and declaring globals above/below the suspect variable I found that ravioli would not find globals below a variable that had been initialized.  So ravioli did not detect any globals in this code:
u8 factoryCode[4] = {0,1,1,2};
u64 test1;
u64 test2;

But found all 3 globals in this code:
u8 factoryCode[4];
u64 test1;
u64 test2;

There must be more issues with how Ravioli is looking for globals because Ravioli is still not picking up the dozens of globals declared throughout my poorly written source file.

**Comment by mchernosky** [comment]
Thank you @shanemmattner, this is great feedback!

Regarding this:
> There must be more issues with how Ravioli is looking for globals because Ravioli is still not picking up the dozens of globals declared throughout my poorly written source file.

Can you tell me more specifically how some of them are declared?

**Comment by mchernosky** [comment]
Hi @shanemmattner, after a bit more testing, I think the issue has to do with multiple initializer lists enclosed in brackets: `{}`. For example something like this:
```
u8 array1[4] = {1,2,3,4};
u8 array2[4] = {5,6,7,8};
```
won't find array2 as a global.
