### ISSUE TITLE
Not compatible with Python 2

### ISSUE THREAD

**Issue by Xenoamor** [ElectronVector/ravioli#4]
I get the following when using it on windows and a similar one on linux
```
c:\project>ravioli
Traceback (most recent call last):
  File "c:\gitlab\toolchain\windows\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\gitlab\toolchain\windows\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Gitlab\Toolchain\windows\python27\Scripts\ravioli.exe\__main__.py", line 5, in <module>
  File "c:\gitlab\toolchain\windows\python27\lib\site-packages\ravioli\ravioli.py", line 66
    print("    ", end='')
                     ^
SyntaxError: invalid syntax
```

Is this Python 3 only or something?

**Comment by gustavovelascoh** [comment]
You are right, that syntax is not available on Python2 as print is not a function. check [this question on SO](https://stackoverflow.com/questions/2456148/python-print-end) about that.

If you can't use Python3, a workaround could be to include `from __future__ import print_function` in ravioli.py, which is the file generating the error. But I'm not sure if there are more incompatibilities with Python2

**Comment by mchernosky** [comment]
Thanks @Xenoamor. Yeah, I haven't done anything for Python 3 compatibility. I've updated the name of this issue to reflect that this is the real problem.

**Comment by Xenoamor** [comment]
I'm not sure this is worth resolving anyway. Python 2 is EOF in a few months

**Comment by mchernosky** [comment]
Python 2 is not planned to be supported as [it went end-of-life on Jan 1, 2020](https://www.python.org/doc/sunset-python-2/).

**Comment by mchernosky** [comment]
Python 2 is not planned to be supported as [it went end-of-life on Jan 1, 2020](https://www.python.org/doc/sunset-python-2/).
